excluded:
  - build
  - DerivedData
  - vendor
  - Snapshot UITests (iOS)/SnapshotHelper.swift

disabled_rules:
  - line_length
  - weak_delegate

opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - private_outlet
  - sorted_imports

type_name:
  max_length: 60

identifier_name:
  min_length:
    error: 4
  max_length: 60
  excluded:
    - age
    - app
    - dto
    - id
    - job
    - lhs
    - rhs
    - tab
    - url