# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submit_for_review(true)
automatic_release(true)
skip_metadata(true)
skip_binary_upload(true)
skip_screenshots(true)
