# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  xcversion(version: "12.0")
end

platform :ios do
  desc "Lint"
  private_lane :lint do
    swiftlint
  end

  desc "Get certificate and provisioning profiles"
  private_lane :certificates do
    cert
    sigh(app_identifier: "uk.co.adam-young.Movies")
    sigh(app_identifier: "uk.co.adam-young.Movies.watchkitapp")
    sigh(app_identifier: "uk.co.adam-young.Movies.watchkitapp.watchkitextension")
    sigh(app_identifier: "uk.co.adam-young.Movies.ioswidgets")
  end

  desc "Run Tests"
  lane :test do
    scan(scheme: "Movies (iOS)", derived_data_path: '.build')
  end

  desc "CI Build"
  lane :ci do
    lint
    # gym(scheme: "Movies (iOS)", skip_archive: true, skip_codesigning: true, derived_data_path: '.build')
    test
  end

  desc "Beta"
  lane :beta do
    lint
    test
    certificates
    gym(scheme: "Movies (iOS)", derived_data_path: '.build')
  end
end

