# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  setup_ci
end

platform :ios do
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(type: "appstore")
    match(type: "development")
  end

  desc "Runs all tests"
  lane :test do
    scan
  end

  desc "Build"
  lane :build do
    match(type: "appstore")
    gym
  end

  desc "PR Build"
  lane :pr do
    match(type: "appstore")
    swiftlint
    disable_automatic_code_signing
    gym(codesigning_identity: "Apple Distribution")
    scan
    enable_automatic_code_signing
  end

  desc "Upload to TestFlight"
  lane :beta do
    # ensure_git_branch(branch: "main")
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
    )
    disable_automatic_code_signing
    gym(codesigning_identity: "Apple Distribution")
    gym
    enable_automatic_code_signing
    testflight
  end
end

platform :mac do
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(type: "appstore")
    match(type: "development")
  end

  desc "Runs all tests"
  lane :test do
    scan
  end

  desc "Build"
  lane :build do
    match(type: "appstore")
    gym
  end

  desc "CI Build"
  lane :ci do
    match(type: "development")
    swiftlint
    scan
    gym(skip_archive: true, skip_codesigning: true)
  end
end
