# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  xcversion(version: "12.0")

  create_keychain(
    name: "movies_keychain",
    password: "movies",
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end

platform :ios do
  desc "Lint"
  private_lane :lint do
    swiftlint
  end

  desc "Certificates"
  private_lane :certificates do
    create_keychain(
      name: "movies_keychain",
      password: "movies",
      unlock: true,
      timeout: false
    )

    match(
      type: "appstore",
      keychain_name: "movies_keychain",
      keychain_password: "movies",
      readonly: is_ci,
      app_identifier: "uk.co.adam-young.Movies,uk.co.adam-young.Movies.watchkitapp,uk.co.adam-young.Movies.watchkitapp.watchkitextension,uk.co.adam-young.Movies.ioswidgets"
    )
  end

  desc "Build"
  lane :build do
    certificates
    # gym(scheme: "Movies (iOS)", derived_data_path: "DerivedData")
    gym(scheme: "Movies (iOS)")
  end

  desc "Run Tests"
  lane :test do
    # scan(scheme: "Movies (iOS)", derived_data_path: "DerivedData")
    scan(scheme: "Movies (iOS)")
  end

  desc "CI Build"
  lane :ci do
    lint
    build
    test
  end

  desc "Upload to TestFlight"
  lane :beta do
    # ensure_git_branch(branch: "main")
    set_build_number_repository
    build
    testflight
  end
end

after_all do
  delete_keychain(
    name: "movies_keychain"
  )
end
