name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testflight:
    name: TestFlight
    runs-on: macos-latest
    environment: TestFlight
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: DerivedData/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('Movies.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and Upload to TestFlight
        run: fastlane ios beta
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
