name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-and-test:
    runs-on: macos-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache DerivedData
      uses: actions/cache@v1
      with:
        path: DerivedData
        key: ${{ runner.os }}-DerivedData
        restore-keys: ${{ runner.os }}-DerivedData

    - name: Install dependencies
      run: |
          brew upgrade swiftlint || brew install swiftlint || true
          brew upgrade fastlane || brew install fastlane || true

    - name: Run tests
      run: fastlane ios ci
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
