name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-and-test:
    runs-on: macos-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cache RubyGems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-

    - name: Cache DerivedData
      uses: actions/cache@v1
      with:
        path: DerivedData
        key: ${{ runner.os }}-DerivedData
        restore-keys: ${{ runner.os }}-DerivedData

    - name: Install dependencies
      run: |
          brew upgrade swiftlint || brew install swiftlint || true
          gem install bundler --no-document || echo "failed to install bundle";
          bundle config set deployment 'true';
          bundle config path vendor/bundle;
          bundle install || echo "failed to install bundle";

    - name: Run tests
      run: bundle exec fastlane ios ci
