name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache vendor/bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          brew bundle

      - name: Build and Test
        run: bundle exec fastlane ios pr
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
