name: TestFlight

on:
  push:
    branches:
      - master

jobs:
  testflight:
    name: TestFlight
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache DerivedData
        uses: actions/cache@v1
        with:
          path: DerivedData
          key: ${{ runner.os }}-DerivedData
          restore-keys: ${{ runner.os }}-DerivedData

      - name: Cache vendor/bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          brew bundle

      - name: Build and Upload to TestFlight
        run: bundle exec fastlane ios beta
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
